optimus_manager/optimus_manager_client.py, optimus_manager/var.py
We can check the current mode (either *nvidia* or *intel*) by executing `glxinfo | grep NVIDIA` and see if the output is non-empty or not (or to check if the return code is 0 or 1). This leads to another switching feature that is able to switch to the other mode (*intel* to *nvidia* or vice versa).
However, to be able to check the current mode, the client first needs to install `glxinfo` or `mesa_demos` package.
=> [Feature request] Add auto mode check capability

README.md, optimus_manager/checks.py, optimus_manager/login_managers.py, optimus_manager/optimus_manager_client.py, optimus_manager/optimus_manager_setup.py, optimus_manager/switching.py
This is the solution for stopping X servers in GDM: we force stop them. Note that `gdm.service` must remain intact, or else we'll have to manually switch to a different virtual terminal before switching back to tty1 for the login screen to appear. (#4)
=> Force kill Xorg server when using GDM

optimus_manager/envs.py, optimus_manager/optimus_manager_setup.py
A little of backstory, after adding the X server killing, my graphics switching has been inconsistent. Sometimes the application worked fine, sometimes it would need manual intervention or even hard shutting down. Also, my PC has a big performance hit _everytime_ I use the application, which is not the case when I used `nvidia_xrun`.
This commit removes the annoying race between optimus_manager_setup killing X servers and the login manager respawning these X servers. This race is probably the cause of such behaviors, including the performance hog. Also, this removes the `XORG_KILLING_DELAY` variable, since it might be a consequence of the race itself.
EDIT: Actually, after rebooting a few times, the inconsistency is back. At least this time there's no more performance hog of any kind. And …
=> Move X servers killing from the starting of login managers to the stopping of them

optimus_manager/login_managers.py
It currently displays as "configureyour" & "youuse"
Might consider multi-line strings (""" """) and Python 3 string interpolation ("{}".format(thing) / f"{thing}")
=> added whitespaces in login manager message

optimus_manager/optimus_manager_setup.py
Firstly, this safely remove the current loginctl session, which the previous method of Xorg killings couldn't do.
Secondly, this safely terminates the user's processes before abruptly killing more "stubborn" processes such as X servers. This may be a safer approach comparing to killing the X servers only.
Also by stopping the systemd-logind service, we may prevent nvidia_drm module refusing to stop, which makes switching from nvidia to intel mode difficult ([source](https://github.com/Witko/nvidia-xrun/issues/32)).
=> Make use of loginctl's terminate-session instead of Xorg killings

README.md, desktop/optimus-manager-systray.desktop, icon/intel.svg, icon/nvidia.svg, optimus_manager/optimus_manager_systray.py, setup.py
Adds a QT systray to easily switch between GPUs.
Now depends on `python-pyqt5` - though if you wanted, it could just be optionally :)
Icons are from FlatWoken, which is released under a CC BY SA license. I'm not yet sure how to properly credit that in AUR packages? A small note in the readme might be enough?
Also requires that the .desktop file, be installed to /usr/share/applications/ in the AUR PKGBUILD.
Here's how it looks on my XFCE desktop panel:
Feel free to give any feedback/request changes before merging, I started just writing it for myself, but thought I might as well submit it upstream.
=> Add a systray

optimus_manager/xorg.py
Just a bug fix. This seems to be the only reason I wasn't able to switch after the 0.7 update.
=> Assign PIDs to the commands' stdout instead of the commands' processes

optimus_manager/pci.py
Xorg expects a different format for PCI bus IDs than the one provided by `lspci`. According to `man xorg.conf` they have to start with `PCI:` and they should use decimal numbers without leading zeroes instead of hexadecimal numbers.
This fixes #65.
=> Fix PCI bus ID format for Xorg

optimus_manager/sessions.py
- Currently, optimus-manager only restarts KDE, GNOME and XFCE.
- Get deepin's dbus object and call RequestLogout() to restart the DE.
Test: Switch GPUs; Display Manager restarts and GPU switches correctly.
System Config: DeepinDE + LightDM on ArchLinux
- iGPU: Intel HD 620
- dGPU: NVIDIA 940 MX
Signed-off-by: Kshitij Gupta <kshitijgm@gmail.com>
=> sessions: Add support for restarting DeepinDE

scripts/prime-offload, scripts/prime-switch, scripts/prime-switch-boot
I've seen that `prime-switch-boot` (and co. scripts) fails if the directory `/var/log/optimus-manager` doesn't exist.
=> Verify that /var/log/optimus-manager directory exists

README.md, config/nvidia-disable.sh, config/nvidia-enable.sh, optimus-manager.conf, optimus_manager/envs.py, optimus_manager/kernel.py, package/PKGBUILD
hi,
This PR enables users to execute custom commands via two new script files (nvidia-enable.sh / nvidia-disable.sh) when using switching=none. This enables users of devices on which bbswitch isn't working to manually enable or disable the gpu by executing custom commands before loading or after unloading the nvidia kernel modules.
=> add support to execute custom commands for nvidia power management

optimus_manager/kernel.py
This PR fixes two issues:
1) errors in gpu switch log reporting that the nvidia gpu is not visible on the pci bus when using the custom power enable / disable scripts.
2) prevent the "bbswitch module not found" error causing the switching to fail when bbswitch was not installed (fix #136). This also addresses the ''bbswitch is required'' issue reported by @yaliv in #133. However this does not improve the behavior as reported in #137. I don't know what the right behavior would be, as I don't use bbswitch.
=> fix nvidia card not visible in pci bus and bbswitch unloading errors

optimus-manager.conf, optimus_manager/config_schema.json, optimus_manager/xorg.py
Using the PRIME Render offload by NVIDIA (see [this doc](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html)) needs the latest xorg-server (which can be installed from the AUR with the packages `xorg-server-git` and `xorg-server-common-git`). But this will prevent the nvidia driver from loading up because of an ABI version mismatch.
This PR adds an `ignore_abi` in the NVIDIA settings that will add the proper server flags in the xorg.conf file. When used, the ABI version mismatch is ignored by the nvidia driver and it loads up fully, allowing anyone to now use NVIDIA PRIME Render offload with the proper environment variables.
=> Adding a way to set the IgnoreABI flag on the NVIDIA driver

optimus_manager/sessions.py
Hello,
Thanks a lot for optimus-manager. I discovered it recently, it works great and it's well documented.
I use LXDE and I'd love for optimus-manager to handle auto logout for it. So here is some sample code to logout from LXDE.
As I'm not a python developer I don't know how to test this though, so I just added this via the GitHub UI… 
PS: as a side note, I tried making optimus-manager work with LXDM (LXDE display manager) without success. I may be wrong here, but I concluded it was not possible, because of the way the [event-based scripts](https://wiki.archlinux.org/index.php/LXDM#Configuration) are handled by LXDM. I ended up switching to LightDM and it worked perfectly. If you think saying that in the docs would be useful I'd be happy to add a note somewhere, let me know.
=> Autologout: add support for LXDE

optimus_manager/client/__init__.py
I was getting a little annoyed when I accidentally press enter on my optimus-manager scripts and still continuing execution despite getting aborted, so I thought I'd make this pull request.
=> Make entering 'n' or nothing when trying to switch GPUs return a return code of 1

optimus_manager/xorg.py
This should fix the exception mentioned in :
https://github.com/Askannz/optimus-manager/issues/109#issuecomment-707358215
The exception is thrown because `envs.XSETUP_SCRIPTS_PATHS` doesn't implement a dict element with `amd` key (since there is no xsetup-script for amd). So let's use `integrated` instead.
=> fix exception because of non-existent dict key

README.md
The current wording is potentially confusing for  users running a kernel
other than mainline - see issue #381 as an example.
=> README: mention custom `nvidia` packages

optimus_manager/sessions.py
Qtile has changed the way their cmd works.
Currently on both stable and latest qtile, optimus-manager returns ```Unknown command: qtile-cmd```
More info on ```qtile cmd-obj```:
http://docs.qtile.org/en/latest/manual/commands/shell/qtile-cmd.html (latest)
http://docs.qtile.org/en/stable/manual/commands/shell/qtile-cmd.html (stable)
=> Update qtile logout command

optimus_manager/checks.py
I analyzed the journal and code of optimus-manager and found that a large amout of time is wasted by `modinfo` in `checks.py`, which can be very slow if used without any parameter. I replaced it with `modinfo -n` and the startup time was improved from ~6s to ~1s on my laptop.
=> Improve startup time by using "modinfo -n" to detect modules

README.md
Not sure if this is what you meant to write, but the current format looks a bit off IMO.
P.S. IDK how to propose edits to the Wiki, but I think it would be great to add a link to https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options on [this section](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#configuration-1--dynamic-power-management-inside-the-nvidia-driver-runtime-d3-power-management), particularly when mentioning how one could read the config file for the difference between `fine` and `coarse`. Not sure how it got to this point, but the config file I initially got had none of those comments.
=> Fixed link to config file on GitHub

optimus-manager.conf, optimus_manager/config_schema.json, optimus_manager/xorg.py
I had this problem that when I switched to NVIDIA mode and logged out, SDDM was just black and my screen was completely off (even its backlight was turned off). I had experience with `nvidia-xrun` and its default configuration always worked for me. The only way for `optimus-manager` to work, was to only use "integrated" and "hybrid" modes.
After comparing xorg configurations from `optimus-manager` and `nvidia-xrun`, it turned out that `nvidia-xrun` always uses `modesetting` as driver for "integrated" GPU, while `optimus-manager` had no option to "use intel driver when in integrated mode, use modesetting when in NVIDIA mode".
This pull request adds a "hybrid" driver for integrated GPUs that has solved the problem for me.
One would just set the `driver` option for `intel` to `hybrid` to …
=> Added a hybrid driver mode for xorg integrated driver

optimus_manager/sessions.py
@es20490446e 
Hello, apologies for my bad english.
I just found out that after an update to kde plasma 6, the autologout function wont work anymore on my machine. The output of my `journalctl` show : 
`ArchLinux ksmserver[29637]: qt.dbus.integration: QDBusConnection: couldn't handle call to logout, no slot matched`
`ArchLinux ksmserver[29637]: qt.dbus.integration: Could not find slot KSMServerInterfaceAdaptor::logout`
Then i found out that the new plasma 6 deprecated the old ksmserver API for the logout method : 
[https://discuss.kde.org/t/logout-reboot-and-shutdown-using-the-terminal/743/9](https://discuss.kde.org/t/logout-reboot-and-shutdown-using-the-terminal/743/9)
So i just modified and updated the logout call API from using ksmserver to Shutdown, and now this works great now on …
=> change the kde plasma logout service call

optimus_manager/xorg.py
Add missing sections in the X.org config file to make the "integrated" mode work as X.org was refusing to start.
The "Device" section was seemingly not enough. X.org needed the "ServerLayout", "Monitor" and "Screen" sections to be present.
Tested on Manjaro 25 with a Lenovo Legion 5 laptop.
=> Add missing sections in the X.org config file for "integrated" mode
